#! /bin/sh

##Set timeout of sudo to 0.
sudo bash -c "echo \"Defaults passwd_timeout=0\" >> /etc/sudoers.d/01_no_timeout"

##Set dpms off to keep screen on.
xset -dpms

##Disable Unity lock
gsettings set org.gnome.desktop.screensaver lock-enabled false

##Enable wired networking.
for devices in $(ip -o link show|grep ether| grep ' UP '| cut -d':' -f2); do nmcli device connect $devices;done

##Set repos to correct sources.
sudo curl https://repogen.simplylinux.ch/txt/xenial/sources_d5ac34000894660acfcd90df104af1f015d54a1d.txt | sudo tee /etc/apt/sources.list

##Update packages and upgrade install hw info tool.
sudo apt update
sudo apt upgrade -y
sudo apt install inxi -y

##Autoinstall proprietary drivers.
sudo ubuntu-drivers autoinstall

##Install xorg and kernel from LTS hardware enablement
sudo apt install --install-recommends -y xserver-xorg-hwe-16.04

##Disable eth0 for WiFi testing.
foo=$(nmcli dev wifi list | wc -l)
if [ ! -z $foo ]; then
    if [ $foo -gt 0 ]; then
        for devices in $(ip -o link show|grep ether| grep ' UP '| cut -d':' -f2); do nmcli device disconnect $devices;done
    fi
fi

##Connect to freegeek SSID.
nmcli dev wifi connect 'freegeek2' password '@freegeek'

##Open youtube.com/simonscat in Firefox.
su -c "nohup firefox https://www.youtube.com/watch?v=TayIfVa0QPs & sleep 60" freegeek

##Clean up sudo timeout and nohup.out
sudo rm /etc/sudoers.d/01_no_timeout
rm /home/freegeek/nohup.out

##Set dpms back on as normal.
xset +dpms

##Enable Unity lock.
gsettings set org.gnome.desktop.screensaver lock-enabled true

##Print inxi to thermal for specs.
inxi -bc 0 | lp -d thermal   

##Hi mom.
