#! /bin/sh

##Set dpms off to keep screen on.
xset -dpms force off

##Set repos to correct sources.
curl https://repogen.simplylinux.ch/txt/xenial/sources_d5ac34000894660acfcd90df104af1f015d54a1d.txt | sudo tee /etc/apt/sources.list

##Update packages and upgrade install hw info tool.
apt update && apt upgrade -y && sudo apt install inxi -y

##Autoinstall proprietary drivers.
sudo ubuntu-drivers autoinstall

##Disable eth0 for WiFi testing.
for devices in $(ip -o link show|grep ether| grep ' UP '| cut -d':' -f2); do nmcli device disconnect $devices;done

##Connect to freegeek SSID.
nmcli dev wifi connect 'freegeek2' password '@freegeek'

##Open youtube.com/simonscat in Firefox.
nohup firefox https://www.youtube.com/watch?v=TayIfVa0QPs & sleep 180

##Run inxi to get system info for certification.
inxi -b

##Enable wired networking.
for devices in $(ip -o link show|grep ether| grep ' UP '| cut -d':' -f2); do nmcli device connect $devices;done

##Set dpms back on as normal.
xset -dpms force on
